language: java
install: skip

os: linux
dist: focal

services:
  - docker

script:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - chmod +x $TRAVIS_BUILD_DIR/install-jdk.sh
  - export JAVA_HOME=$HOME/openjdk16
  - $TRAVIS_BUILD_DIR/install-jdk.sh -F 16 --target $JAVA_HOME
  - chmod +x gradlew
  - ./gradlew assemble
  - cd Server
  - sudo docker build -t calebeardley/monopoly:1.0 .
  - sudo docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
  - sudo docker push calebeardley/monopoly:1.0